version: '3.8'
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8080:8080"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: quest
      RABBITMQ_DEFAULT_PASS: guest