version: '3.8'
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  app-service:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
      - dynamodb