server:
  port: 8082
spring:
  application:
    name: "statistics-stats"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: "rabbitmq"
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
aws:
  dynamodb:
    endpoint: "http://dynamodb:8000"
  region: "us-east-1"
app:
  rabbitmq:
    exchange:
      stats: "stats-exchange"
    routing-key:
      stats: "stats-routing-key"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
commons:
  jms:
    output-concurrency: 10
    output-queue: "DEV.QUEUE.1"
    producer-ttl: 0
    reactive: true
ibm:
  mq:
    channel: "DEV.APP.SVRCONN"
    user: "app"
